### PR TITLE
comfort yara 3.6.0

### PR DESCRIPTION
**Pull request by Ryuchen**

### CODE REVIEW

**Comment by Neo23x0** [comment]
You mean "comfort YARA before 3.6.0". Changing the `pe.imphash()` values to dummy values disables the detection via imphash.

**Comment by Ryuchen** [comment]
yes

**Comment by Neo23x0** [comment]
Why should I commit this to the "master" branch?

**Comment by anthonybais777** [comment]
I have issues with my code!

**Pull request closed without merging**
