### PR TITLE
46 new webshell rules

### PR DESCRIPTION
**Pull request by 2d4d**
sorry, they use private rules so they won't properly show the matching strings in thor & loki but it's just convenient

### CODE REVIEW

**Comment by Neo23x0** [comment]
Can't merge this rule set as it contains "private" rules, which are difficult to handle (dependencies have to be resolved, split meta data) and therefore not yet supported by our internal QA system that processes the rules for THOR lite, which also pulls from this repo. 

I am sure, other projects and vendors frequently pull this repo as well. I don't know how many projects would break due to these rules.

**Comment by 2d4d** [comment]
hmmm, I could probably distribute the strings and conditions from the private rules to each individual rule before publishing.

**Comment by Neo23x0** [comment]
Yeah, I think redundancy is a lesser problem than private rules

**Comment by 2d4d** [comment]
it works, gen_webshell_no_priv.yar finds the same 3177 webshells as the original rule

**Comment by 2d4d** [comment]
fails because I didn't remove gen_webshell.yar (SyntaxError: line 67605: duplicated identifier "webshell_generic_os_strings"), needs some beauty work anyway :)

**Comment by Neo23x0** [comment]
Okay, after a series of private chats and false positive tuning, we can finally merge this awesome set of rules

**Pull request merged**
