### PR TITLE
WildNeutron False Positive Fix

### PR DESCRIPTION
**Pull request by wesdawg**
chickenkiller is dynamic DNS, not WildNeutron specific.

### CODE REVIEW

**Comment by Neo23x0** [comment]
What are the false positives that contain that string?

**Comment by wesdawg** [comment]
@Neo23x0 https://www.hybrid-analysis.com/sample/e8156ec1706716cada6f57b6b8ccc9fb0eb5debe906ac45bdc2b26099695b8f5?environmentId=100
This malware is not WildNeutron

**Comment by Neo23x0** [comment]
I created a new rule that covers your sample.

**Comment by wesdawg** [comment]
Thanks

**Pull request merged**
