### PR TITLE
Update gen_github_net_redteam_tools_guids.yar 

### PR DESCRIPTION
**Pull request by ruppde**
add:
HKTL_NET_GUID_Sharpcat
HKTL_NET_GUID_SharpNamedPipePTH

### CODE REVIEW

**Comment by Neo23x0** [comment]
Did you add these rules in internal MRs, too?

**Comment by ruppde** [comment]
no

**Comment by Neo23x0** [comment]
Are they still not in our internal rule set?

**Comment by ruppde** [comment]
they are, you can merge

**Pull request merged**
